#!/bin/bash

ENVFILE='.pico_env'
BUILD_DIR='build.arm'


cat << EOF > $ENVFILE

. ~/.bashrc

if [[ -e .ssh-agent.conf ]]; then
	. .ssh-agent.conf
else
	if [[ -e github-id ]]; then
		ssh-agent -s > .ssh-agent.conf
		. .ssh-agent.conf
		ssh-add github-id
	fi
fi

export PICO_SDK_PATH=~/pico-sdk

mkdir -p $BUILD_DIR
cd $BUILD_DIR
cmake ..

EOF

/bin/bash --init-file $ENVFILE -s
rm -f $ENVFILE

AGENT_PID=`cat .ssh-agent.conf | grep SSH_AGENT_PID | awk -F= '{ print \$2 }' | awk "-F;" '{ print \$1 }'`
kill $AGENT_PID
rm -f .ssh-agent.conf

